version: '3.2'
services:
  mysql:
    image: mysql:5.7
    ports:
    - 8083:3306
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

  tribalknow:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - MYSQL_HOST=mysql
    command: bundle exec rails s -p 3000 -b 0.0.0.0
    volumes:
      - .:/home/app/tribalknow
    ports:
      - "3000:3000"
    depends_on:
      - mysql

