# encoding: utf-8
# Autogenerated by the db:seed:dump task
# Do not hesitate to tweak this to your needs

Topic.create([
  { :parent_topic_id => 1, :name => "bash", :description => "", :tags => ["unix", "cli", "bash"] },
  { :parent_topic_id => nil, :name => "unix", :description => "unix topics", :tags => ["unix"] },
  { :parent_topic_id => 1, :name => "Processes", :description => "", :tags => ["unix", "process", "bash"] }
], :without_protection => true )


